name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        else
          echo "No package.json found, skipping npm install"
        fi
        
    - name: Run tests
      run: |
        if [ -f package.json ] && grep -q '"test"' package.json; then
          npm test
        else
          echo "No test script found in package.json, skipping tests"
        fi
        
    - name: Build
      run: |
        if [ -f package.json ] && grep -q '"build"' package.json; then
          npm run build
        else
          echo "No build script found in package.json, skipping build"
        fi
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example:
        # - Deploy to a server
        # - Deploy to a cloud service like AWS, Azure, or Google Cloud
        # - Deploy to GitHub Pages
        
        echo "Deployment completed successfully!"
